LIBRETRO_COMM_DIR := $(CORE_DIR)/libretro/libretro-common
INCFLAGS := -I$(CORE_DIR)/libretro  -I$(CORE_DIR) -I$(LIBRETRO_COMM_DIR)/include

ifneq (,$(findstring msvc2003,$(platform)))
INCFLAGS += -I$(LIBRETRO_COMM_DIR)/include/compat/msvc
endif

# Core
SOURCES_C = libretro.c fake6502.c
